name: Test CI workflow

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
jobs:
  run-train-predict:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Copy my repo to vm 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run training script
        run: python src/train.py --data data/sentiments.csv --out models/sentiment.joblib

      - name: Run prediction script
        run: python src/predict.py "That was the best" "I'm happy" "Whoa! That's terrible"
      
      - name: Run tests
        run: pytest -v test/
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Copy my repo to vm 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run ruff linter
        run: ruff check .
      
      - name: Run ruff formatter
        run: ruff format . --check
  type-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Copy my repo to vm 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run mypy type checker
        run: mypy src/ test/
    build-and-deploy-docker-image:
    runs-on: ubuntu-latest
    needs: [run-train-predict, lint-and-format, type-check]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SENTIMENTPROJECT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis:latest

  