name: Test CI workflow

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
jobs:
  run-train-predicz:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Copy my repo to vm 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python src/train.py --data data/sentiments.csv --out models/sentiment.joblib
      
      - name: Run tests
        run: pytest -v test/