name: Test CI workflow

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
jobs:
  run-train-predict:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Copy my repo to vm 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run training script
        run: python src/train.py --data data/sentiments.csv --out models/sentiment.joblib

      - name: Run prediction script
        run: python src/predict.py "That was the best" "I'm happy" "Whoa! That's terrible"
      
      - name: Run tests
        run: pytest -v test/
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Copy my repo to vm 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run ruff linter
        run: ruff check .
      
      - name: Run ruff formatter
        run: ruff format . --check
  type-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Copy my repo to vm 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run mypy type checker
        run: mypy src/ test/
  